api_platform:
  oauth:
    # To enable or disable OAuth.
    enabled: true

    # The OAuth client ID.
    clientId: 'c80d228dcae0384a917b271d4fce9ace'

    # The OAuth client secret.
    clientSecret: '025b2858dad24c936cb09e04ec9a8a846f7aa71ce77e91b2a42ba91f99fd4b60c043bb6ca19f203fc14bb57edd7c2a415ed87c65b0983c4e4b0c159f98aeafe8'

    # The OAuth type.
    type: 'oauth2'

    # The OAuth flow grant type.
    flow: 'password'

    # The OAuth token url.
    tokenUrl: '/token'

    # The OAuth authentication url.
    authorizationUrl: '/oauth/v2/auth'

    # The OAuth scopes.
    scopes: []